name: Test and Merge to Main

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run dag integrity tests
      run: |
        pytest --maxfail=1 --disable-warnings

    - name: Run PEP 8 check
      run: |
        find plugins dags -type f -name "*.py" ! -path "dags/country_interested.py" | xargs flake8 --max-line-length=200

    - name: Create Pull Request
      if: success()
      uses: repo-sync/pull-request@v3
      with:
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}