name: Test and Merge to Main

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run dag integrity tests
      run: |
        pytest --maxfail=1 --disable-warnings
    - name: Run PEP 8 check
      run: |
        find plugins dags -type f -name "*.py" ! -path "dags/country_interested.py" | xargs flake8 --max-line-length=200
  create-pull-request:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Automated PR from develop to main"
        branch: main
        title: "Automated PR from develop to main"
        body: "This PR is created automatically to merge changes from develop to main after passing all tests and linting."
        labels: "automerge"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}